 sqlite3 db.sqlite3 < /workspaces/BIRD_Quick_Start/mysite/sql/ABSTRCT_INSTRMNT_RL.sql
 sqlite3 db.sqlite3 < /workspaces/BIRD_Quick_Start/mysite/sql/CLLTRL_NN_FNNCL_ASST_ASSGNMNT.sql
 sqlite3 db.sqlite3 < /workspaces/BIRD_Quick_Start/mysite/sql/CLLTRL.sql
 sqlite3 db.sqlite3 < /workspaces/BIRD_Quick_Start/mysite/sql/CRDT_FCLTY_ENTTY_RL_ASSGNMNT.sql
 sqlite3 db.sqlite3 < /workspaces/BIRD_Quick_Start/mysite/sql/CRDT_FCLTY.sql
 sqlite3 db.sqlite3 < /workspaces/BIRD_Quick_Start/mysite/sql/CSH_HND.sql
 sqlite3 db.sqlite3 < /workspaces/BIRD_Quick_Start/mysite/sql/ENTTY_RL.sql
 sqlite3 db.sqlite3 < /workspaces/BIRD_Quick_Start/mysite/sql/EXCHNG_TRDBL_DRVTV_PSTN.sql
 sqlite3 db.sqlite3 < /workspaces/BIRD_Quick_Start/mysite/sql/FNDMNTL_RVW_TRDNG_BK_STNDRD_APPRCH_RSK_MSR_ETD_PSTNS.sql
 sqlite3 db.sqlite3 < /workspaces/BIRD_Quick_Start/mysite/sql/FNDMNTL_RVW_TRDNG_BK_STNDRD_APPRCH_RSK_MSR_FR_SCRTY_PSTNS.sql
 sqlite3 db.sqlite3 < /workspaces/BIRD_Quick_Start/mysite/sql/FNDMNTL_RVW_TRDNG_BK_STNDRD_APPRCH_RSK_MSR_OTC_PSTNS.sql
 sqlite3 db.sqlite3 < /workspaces/BIRD_Quick_Start/mysite/sql/FNNCL_CNTRCT.sql
 sqlite3 db.sqlite3 < /workspaces/BIRD_Quick_Start/mysite/sql/INSTRMNT_ENTTY_RL_ASSGNMNT.sql
 sqlite3 db.sqlite3 < /workspaces/BIRD_Quick_Start/mysite/sql/INSTRMNT.sql
 sqlite3 db.sqlite3 < /workspaces/BIRD_Quick_Start/mysite/sql/LNG_SCRTY_PSTN_PRDNTL_PRTFL_ASSGNMNT_ACCNTNG_CLSSFCTN_FNNCL_ASSTS_ASSGNMNT.sql
 sqlite3 db.sqlite3 < /workspaces/BIRD_Quick_Start/mysite/sql/LNG_SCRTY_PSTN_PRDNTL_PRTFL_ASSGNMNT.sql
 sqlite3 db.sqlite3 < /workspaces/BIRD_Quick_Start/mysite/sql/NN_FNNCL_ASST.sql
 sqlite3 db.sqlite3 < /workspaces/BIRD_Quick_Start/mysite/sql/NN_FNNCL_LBLTY.sql
 sqlite3 db.sqlite3 < /workspaces/BIRD_Quick_Start/mysite/sql/PRTY.sql
 sqlite3 db.sqlite3 < /workspaces/BIRD_Quick_Start/mysite/sql/RSK_FAC_SA.sql
 sqlite3 db.sqlite3 < /workspaces/BIRD_Quick_Start/mysite/sql/SBSDRY_JNT_VNTR_ASSCT_OTHR_ORGNSTN_ASSGNMNT.sql
 sqlite3 db.sqlite3 < /workspaces/BIRD_Quick_Start/mysite/sql/SCRTY_EXCHNG_TRDBL_DRVTV.sql
 sqlite3 db.sqlite3 < /workspaces/BIRD_Quick_Start/mysite/sql/SCRTY_PSTN.sql
 sqlite3 db.sqlite3 < /workspaces/BIRD_Quick_Start/mysite/sql/SCRTY_PSTN.sql
